// <auto-generated />
using System;
using Apteka.API.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Apteka.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210824101506_SeedDori")]
    partial class SeedDori
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Apteka.API.Models.Dori", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Dorilar");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ccb00df2-8538-46af-83de-ad2aacb873cf"),
                            Name = "Sitromon",
                            Price = 1000m,
                            Quantity = 100
                        },
                        new
                        {
                            Id = new Guid("c1edc814-b6c5-440a-a52b-1a9bb8b655a3"),
                            Name = "Paratsetomol",
                            Price = 500m,
                            Quantity = 50
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
